fix: extract out materialization props (#223)
## Summary
Writing to bigquery partitioned tables involves creating bq temp table
first. The temp table is created within the specified project + dataset
of the destination table however we are running into an issue where the
connector is unable to extract those information from the provided
destination table id:

```

com.google.cloud.spark.bigquery.repackaged.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: Provided dataset is null or empty
  at BigQueryDataSourceWriterModule.provideDirectDataSourceWriterContext(BigQueryDataSourceWriterModule.java:63)
  while locating BigQueryDirectDataSourceWriterContext
```

so let's configure this as writeoptions on our side, which allows the
connector to pick those up.

A successful run:
https://console.cloud.google.com/dataproc/jobs/289ba1b4-b029-42b7-912d-4dad109f5dc9/monitoring?region=us-central1&project=canary-443022
## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update
<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

## Summary by CodeRabbit

- **Refactor**
- Removed utility methods for table and database management in the
application.
	- Simplified build configuration and dependency management.
- Updated data writing configuration for improved integration with
BigQuery.

- **Chores**
- Minor formatting adjustments in build settings for improved
readability.
	- Cleaned up commented dependencies.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->
---
- To see the specific tasks where the Asana app for GitHub is being
used, see below:
  - https://app.asana.com/0/0/1209143482009694

<!-- av pr metadata
This information is embedded by the av CLI when creating PRs to track
the status of stacks when using Aviator. Please do not delete or edit
this section of the PR.
```
{"parent":"main","parentHead":"","trunk":"main"}
```
-->

---------

Co-authored-by: Thomas Chow <thomaschow369@gmail.com>