Add run_gcp_hub_quickstart script for CI testing (#1001)
## Summary

^^^

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update

```
(tmp_chronon) davidhan@Mac: ~/zipline/chronon (davidhan/ZIP-824) $ bash scripts/distribution/run_gcp_hub_quickstart.sh --dev --version 0.1.0+dev.davidhan --hub-url http://localhost:3903
Copying gs://zipline-artifacts-dev/release/0.1.0+dev.davidhan/wheels/zipline_ai-0.1.0+dev.davidhan-py3-none-any.whl to file://./zipline_ai-0.1.0+dev.davidhan-py3-none-any.whl
  Completed files 1/1 | 385.0MiB/385.0MiB | 40.4MiB/s                                                                                                                                                                                         

<<<<<.....................................COMPILE.....................................>>>>>
...
...
Join-s:
  Parsed 7 previously compiled objects.
  Compiled 7 objects from 2 files.
  No new changes detected

GroupBy-s:
  Parsed 8 previously compiled objects.
  Compiled 8 objects from 3 files.
  No new changes detected

StagingQuery-s:
  Parsed 1 previously compiled objects.
  Compiled 1 objects from 1 files.
  No new changes detected

MetaData-s:
  Parsed 4 previously compiled objects.
  Compiled 4 objects from 4 files.
  Updated test.test_team_metadata


<<<<<.....................................BACKFILL.....................................>>>>>
Identified branch: davidhan/ZIP-824


Uploading:

Identified branch: davidhan/ZIP-824
{'workflowId': '224da9a6-5ee2-4578-833b-19c202a84aff'}
224da9a6-5ee2-4578-833b-19c202a84aff
<<<<<.....................................CHECK-WORKFLOW_ID.....................................>>>>>
Attempt 1/10: Checking workflow status...
Workflow response: {"workflowId":"224da9a6-5ee2-4578-833b-19c202a84aff","confName":"gcp.purchases.v1_test__0","mode":"backfill","branch":"davidhan/ZIP-824","user":"davidhan","status":1,"startPartition":"2023-11-30","endPartition":"2023-11-30","nodeExecutions":[{"nodeName":"gcp.purchases.v1_test__0__backfill","nodeHash":"3c2739","startPartition":"2023-11-30","endPartition":"2023-11-30","dependencies":[],"stepRuns":[]}],"terminalNodes":["gcp.purchases.v1_test__0__backfill"]}
Current status: 1 (SUBMITTED)
Status is 1, waiting 30 seconds before retry...
Attempt 2/10: Checking workflow status...
Workflow response: {"workflowId":"224da9a6-5ee2-4578-833b-19c202a84aff","confName":"gcp.purchases.v1_test__0","mode":"backfill","branch":"davidhan/ZIP-824","user":"davidhan","status":2,"startPartition":"2023-11-30","endPartition":"2023-11-30","nodeExecutions":[{"nodeName":"gcp.purchases.v1_test__0__backfill","nodeHash":"3c2739","startPartition":"2023-11-30","endPartition":"2023-11-30","dependencies":[],"stepRuns":[{"runId":"01984787-5408-747c-a303-874b9793129b","startPartition":"2023-11-30","endPartition":"2023-11-30","startTime":"2025-07-26T16:18:27.983Z","status":2,"dependentStepRunIds":[],"jobTrackingInfo":{"jobUrl":"https://console.cloud.google.com/dataproc/jobs/f7b3042b-a4fb-4f26-852c-1376ffa544c0?region=us-central1&project=canary-443022","sparkUrl":"https://dnhkhi3cp5b7xaqo3rsgfheaqa-dot-us-central1.dataproc.googleusercontent.com/yarn/proxy/application_1750716374407_1436"}}]}],"terminalNodes":["gcp.purchases.v1_test__0__backfill"]}
Current status: 2 (RUNNING)
Status is 2, waiting 30 seconds before retry...
Attempt 3/10: Checking workflow status...
Workflow response: {"workflowId":"224da9a6-5ee2-4578-833b-19c202a84aff","confName":"gcp.purchases.v1_test__0","mode":"backfill","branch":"davidhan/ZIP-824","user":"davidhan","status":4,"startPartition":"2023-11-30","endPartition":"2023-11-30","nodeExecutions":[{"nodeName":"gcp.purchases.v1_test__0__backfill","nodeHash":"3c2739","startPartition":"2023-11-30","endPartition":"2023-11-30","dependencies":[],"stepRuns":[{"runId":"01984787-5408-747c-a303-874b9793129b","startPartition":"2023-11-30","endPartition":"2023-11-30","startTime":"2025-07-26T16:18:27.983Z","endTime":"2025-07-26T16:19:16.033Z","status":4,"dependentStepRunIds":[],"jobTrackingInfo":{"jobUrl":"https://console.cloud.google.com/dataproc/jobs/f7b3042b-a4fb-4f26-852c-1376ffa544c0?region=us-central1&project=canary-443022","sparkUrl":"https://dnhkhi3cp5b7xaqo3rsgfheaqa-dot-us-central1.dataproc.googleusercontent.com/yarn/proxy/application_1750716374407_1436"}}]}],"terminalNodes":["gcp.purchases.v1_test__0__backfill"]}
Current status: 4 (FAILED)
Error: Workflow status is 4, exiting with error

```



<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

* **New Features**
* Introduced a script to automate running Zipline AI workflows on Google
Cloud Platform, including environment selection, version control, and
workflow status monitoring.

* **Chores**
* Updated the starting partition date for training set data selection to
November 30, 2023, affecting the time range of events considered in
training sets.
  * Removed an unused variable from an existing GCP quickstart script.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->