Add missing lineage.thrift in wheel gen scripts (#526)
## Summary
Our wheel seems to be broken after we added the lineage.thrift file - 
```
zipline compile --input_path group_bys/search/beacons/listing.py                                             
Traceback (most recent call last):
  File "/Users/pnarang/workspace/zipline/dev_chronon/bin/zipline", line 5, in <module>
    from ai.chronon.repo.zipline import zipline
  File "/Users/pnarang/workspace/zipline/dev_chronon/lib/python3.11/site-packages/ai/chronon/repo/__init__.py", line 15, in <module>
    from ai.chronon.api.ttypes import GroupBy, Join, StagingQuery, Model
  File "/Users/pnarang/workspace/zipline/dev_chronon/lib/python3.11/site-packages/ai/chronon/api/ttypes.py", line 16, in <module>
    import ai.chronon.lineage.ttypes
ModuleNotFoundError: No module named 'ai.chronon.lineage'
```

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update



<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

- **New Features**
- Enhanced the automated generation process to support all Thrift files
in the `api/thrift/` directory, improving efficiency.
- Updated the build routine to streamline the generation of Thrift
files, ensuring consistency and smooth integration.
- Consolidated ignored directory paths in the version control system for
better management.

- **Bug Fixes**
- Removed the deprecated script responsible for generating Python Thrift
files, eliminating associated issues.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->