fix: thrift --gen was outputting incorrectly in a nested fashion (#219)
## Summary

Getting an error in installing the wheel:

```
$ zipline
Traceback (most recent call last):
  File "/Users/gdonovan/development/zipline/.direnv/python-3.11/bin/zipline", line 5, in <module>
    from ai.chronon.repo.zipline import zipline
ModuleNotFoundError: No module named 'ai'
```

Previously as part of building the wheel, we were running:

`davidhan@Davids-MacBook-Pro: ~/zipline/chronon $ thrift --gen py -out
api/py/ai/chronon api/thrift/api.thrift`

but this was actually resulting in:

```
davidhan@Davids-MacBook-Pro: ~/zipline/chronon/api/py/ai/chronon/ai/chronon/api (davidhan/fix_wheel_building) $ pwd
/Users/davidhan/zipline/chronon/api/py/ai/chronon/ai/chronon/api
```

/Users/davidhan/zipline/chronon/api/py/ai/chronon/_**ai/chronon/api**_

- the `ai/chronon/api` is under
`/Users/davidhan/zipline/chronon/api/py/ai/chronon` so it's nested.

We don't want this. We actually want:

/Users/davidhan/zipline/chronon/api/py/**_ai/chronon/api_**

To do this we needed to change the `-out` value to be just `api/py/` 

### Side note
One thing that was helpful in debugging the above `ModuleNotFoundError`
was opening up a python repl at the directory of where `setup.py` was
and running find_packages:

```
davidhan@Davids-MacBook-Pro: ~/zipline/chronon/api/py (davidhan/fix_wheel_building) $ python3
Python 3.13.0 (main, Jan  8 2025, 10:48:30) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import find_packages
>>> find_packages()
[]
```
This should be a red flag if we get back an empty list that even if we
successfully build the wheel, it's not going to install properly.

Doing the fix to the `-out` above to thrift gen fixes the
`../__init__.py` to the correct directories so that a good
`find_packages` output should look like:
```
davidhan@Davids-MacBook-Pro: ~/zipline/chronon (davidhan/fix_wheel_building) $ thrift --gen py -out api/py/ api/thrift/common.thrift
davidhan@Davids-MacBook-Pro: ~/zipline/chronon (davidhan/fix_wheel_building) $ thrift --gen py -out api/py/ api/thrift/api.thrift
davidhan@Davids-MacBook-Pro: ~/zipline/chronon (davidhan/fix_wheel_building) $ thrift --gen py -out api/py/ api/thrift/observability.thrift
davidhan@Davids-MacBook-Pro: ~/zipline/chronon (davidhan/fix_wheel_building) $ 
davidhan@Davids-MacBook-Pro: ~/zipline/chronon (davidhan/fix_wheel_building) $ cd api/py
davidhan@Davids-MacBook-Pro: ~/zipline/chronon/api/py (davidhan/fix_wheel_building) $ python3
Python 3.13.0 (main, Jan  8 2025, 10:48:30) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import find_packages
>>> find_packages()
['ai', 'ai.chronon', 'ai.chronon.scheduler', 'ai.chronon.observability', 'ai.chronon.api', 'ai.chronon.repo', 'ai.chronon.scheduler.utils', 'ai.chronon.scheduler.adapters', 'ai.chronon.scheduler.interfaces', 'ai.chronon.api.common']

```

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update