Exclude rockdbjni from assembled Flink / cloud gcp jars (#334)
## Summary
Hit some errors as our Spark deps pull in rocksdbjni 8.3.2 whereas we
expect an older version in Flink (6.20.3-ververica-2.0). As we rely on
user class first it seems like this newer version gets priority and when
Flink is closing tiles we hit an error -
```
2025-02-05 21:14:53,614 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Tiling for etsy.listing_canary.actions_v1 -> (Tiling Side Output Late Data for etsy.listing_canary.actions_v1, Avro conversion for etsy.listing_canary.actions_v1 -> async kvstore writes for etsy.listing_canary.actions_v1 -> Sink: Metrics Sink for etsy.listing_canary.actions_v1) (2/3) (a107444db4dad3eb79d9d02631d8696e_5627cd3c4e8c9c02fa4f114c4b3607f4_1_56) switched from RUNNING to FAILED on container_1738197659103_0039_01_000004 @ zipline-canary-cluster-w-1.us-central1-c.c.canary-443022.internal (dataPort=33465).
java.lang.NoSuchMethodError: 'void org.rocksdb.WriteBatch.remove(org.rocksdb.ColumnFamilyHandle, byte[])'
	at org.apache.flink.contrib.streaming.state.RocksDBWriteBatchWrapper.remove(RocksDBWriteBatchWrapper.java:105)
```

Yanked it out from the two jars and confirmed that the Flink job seems
to be running fine + crossing over across hours (and hence tile
closures).

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [X] Integration tested
- [ ] Documentation update



<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

- Chores
- Made internal adjustments to dependency management to improve
compatibility between libraries and enhance overall application
stability.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->