Rename dest for UC cannot include the catalog name (#1545)
## Summary

Unity Catalog's rename path is not entirely cooperative on the catalog
aliases. The catalog name is inferred off of the endpoint and then it
expects only the schema and table name to be provided during the rename.
If the catalog name is also provided in the rename we get:

```
SemanticUtils.scala:17: Renaming table: ALTER TABLE <catalog>.<schema>.<table> RENAME TO <catalog>.<schema>.<table>_reuse
TableUtils.scala:343: 
  [1m[38;5;131m---- running query ----[0m

[38;5;172m    ALTER TABLE <catalog>.<schema>.<table> RENAME TO <catalog>.<schema>.<table>_archive_reuse[0m

  ---- call path ----

    catalog.TableUtils.sql(TableUtils.scala:334)
    utils.SemanticUtils.renameTable(SemanticUtils.scala:19)
    utils.SemanticUtils.archiveForReuse(SemanticUtils.scala:42)
    utils.SemanticUtils.checkSemanticHashAndArchive(SemanticUtils.scala:68)
    batch.BatchNodeRunner.$anonfun$runFromArgs$1(BatchNodeRunner.scala:679)
    batch.BatchNodeRunner.runFromArgs(BatchNodeRunner.scala:650)
    batch.BatchNodeRunner$.main(BatchNodeRunner.scala:769)
    batch.BatchNodeRunner.main(BatchNodeRunner.scala)

  ---- end ----

TableUtils.scala:356: Error running query:
org.apache.iceberg.exceptions.BadRequestException: Malformed request: Malformed request: BAD_REQUEST: Namespace must have exactly one level
	at org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:234) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:124) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:108) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:240) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:336) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:297) ~[cloud_aws_lib_deploy.jar:0.0.32]
	at org.apache.iceberg.rest.BaseHTTPClient.post(BaseHTTPClient.java:100) ~[cloud_aws_lib_deploy.jar:0.0.32]
```

Updates the rename to just drop the catalog part as we only rename
within catalog. This works. See:
https://github.com/apache/iceberg/pull/12159/

## Checklist
- [x] Added Unit Tests
- [ ] Covered by existing CI
- [ ] Integration tested
- [ ] Documentation update